// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_gQKS4TQ3dcx36hePn0z4bjdevQ5PYQQ',
    appId: '1:414124391039:web:e38c9d193db90a9c57dd4a',
    messagingSenderId: '414124391039',
    projectId: 'bunkit-2174e',
    authDomain: 'bunkit-2174e.firebaseapp.com',
    storageBucket: 'bunkit-2174e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdZWTaetqAuGchmhE-jjwfSR3nwZqVbi0',
    appId: '1:414124391039:android:2f79cce5fef8605057dd4a',
    messagingSenderId: '414124391039',
    projectId: 'bunkit-2174e',
    storageBucket: 'bunkit-2174e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVsS1uLBXYDBlwzSFBv3lIzyZRrULzHLA',
    appId: '1:414124391039:ios:4315ba5f39a4745057dd4a',
    messagingSenderId: '414124391039',
    projectId: 'bunkit-2174e',
    storageBucket: 'bunkit-2174e.firebasestorage.app',
    iosBundleId: 'com.example.bunkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVsS1uLBXYDBlwzSFBv3lIzyZRrULzHLA',
    appId: '1:414124391039:ios:4315ba5f39a4745057dd4a',
    messagingSenderId: '414124391039',
    projectId: 'bunkit-2174e',
    storageBucket: 'bunkit-2174e.firebasestorage.app',
    iosBundleId: 'com.example.bunkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_gQKS4TQ3dcx36hePn0z4bjdevQ5PYQQ',
    appId: '1:414124391039:web:e83d86b05b51723157dd4a',
    messagingSenderId: '414124391039',
    projectId: 'bunkit-2174e',
    authDomain: 'bunkit-2174e.firebaseapp.com',
    storageBucket: 'bunkit-2174e.firebasestorage.app',
  );
}
